### PR TITLE
Build showcase page

### PR DESCRIPTION
**Pull request by lukalocniskar**
Ability to build deployable showcase page.

### CODE REVIEW

**Comment by Netherdrake** [comment]
Can you please make this work in Docker?

**Comment by Netherdrake** [comment]
https://github.com/reef-defi/reef-ui-kit/commit/42bc43f7e11a5d52aacb9c4628852a506f43aa82

**Comment by lukalocniskar** [comment]
I'll configure it and add to this PR.

**Comment by lukalocniskar** [comment]
@Netherdrake can you please try and build it on server. Tried it with my local reverse proxy.

**Pull request merged**
